# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: prathamesh17170@gmail.com
author_name: Prathamesh Chougale
cloud_provider: vercel
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: app

