name: Pull Request validation

on: [pull_request]


jobs:
  app-contracts-ci:
    name: Run app-contracts validation
    uses: ./.github/workflows/app-contracts-ci.yaml

  app-frontend-ci:
    name: Run app-frontend validation
    uses: ./.github/workflows/app-frontend-ci.yaml

